# Starship Configuration
# Docs: https://starship.rs/config/

add_newline = true

[character]
success_symbol = "[âœ](bold green)"
error_symbol = "[âœ—](bold red)"

[package]
disabled = true # é»˜è®¤ä¸æ˜¾ç¤º package versionï¼ŒæŒ‰éœ€å¼€å¯

[git_branch]
symbol = "ğŸŒ± "

[git_status]
disabled = false

[nodejs]
symbol = "ğŸŸ¢ "

[python]
symbol = "ğŸ "

[java]
symbol = "â˜• "

[golang]
symbol = "ğŸ¹ "

[aws]
symbol = "â˜ï¸  "
